#!/bin/bash

# Create Custom Folder

CUSTOM="${HOME}/.bash_custom"
mkdir ${CUSTOM} && cd ${CUSTOM}

git clone "https://github.com/vivek-x-jha/CustomTerminal"

chmod +x ${CUSTOM}/*.sh

${CUSTOM}/customize_prompt.sh
${CUSTOM}/colorize_ls.sh
${CUSTOM}/git_aliases.sh
